version: '3.3'
services:
  bot:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    restart: unless-stopped

  tunnel:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYzk5MThmMmNhYTA1MDczNmEwNzg2N2U2Zjk2OGMwYTIiLCJ0IjoiOWE5ZTg0YzctZjhiOC00YjVhLTk5MDMtMTdiZjM3ZGEyMDVlIiwicyI6Ik1qZzFNR1ZqWkRrdFltUTROUzAwTjJJNExUa3hPV0V0WVRBM05qTmlaamd6T0dZMyJ9
